# Site settings
# title: Forty
# subtitle: by HTML5 UP

description: RP Lab - PBoC
baseurl: ""
url: "rpgroup.caltech.edu" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6


# Build settings
markdown: kramdown
sass:
  style: compressed
