# Site settings
# title: Forty
# subtitle: by HTML5 UP

description: Physical Biology of the Cell
baseurl: "/forty-jekyll-theme/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6


# Build settings
markdown: kramdown

sass:
  style: compressed
